version: "3.8"
services:
  employee:
    image: employee
    container_name: employee
    stop_grace_period: 2m
    ports: ["8080:8080"]
    environment:
      - _JAVA_OPTIONS=-Xmx1g -Xms1g
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: "curl --silent --output /dev/null http://localhost:8080; if [[ $$? == 0 ]]; then echo 0; else echo 1; fi"
      interval: 100s
      timeout: 10s
      retries: 5
