version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    platform: linux/x86_64
    volumes:
      - /var/db/employee/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employee
      
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp